#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 Krishna Teja Vepa
# One-command reproduction check for the D1 verdict artifact.
#
# What it does, from a clean checkout with no arguments:
#   1. verifies the provenance manifest hashes (committed inputs untampered),
#   2. regenerates d1_corrected_offsets.json in a temp sandbox from the
#      committed inputs (never touching the committed copy), and
#   3. byte-compares the regenerated artifact against the committed one.
#
# Exit 0: byte-identical reproduction. Exit 1: differs (unified diff printed).
# Exit 2: setup problem (missing files / python).
#
# Usage: bash scripts/verify_reproduction.sh
set -u
cd "$(dirname "$0")/.."
REPO="$PWD"
PY="${QME_PY:-python3}"

command -v "$PY" >/dev/null || { echo "verify_reproduction: no python3 on PATH" >&2; exit 2; }
[ -f data/d1_corrected_offsets.json ] || { echo "verify_reproduction: committed artifact missing" >&2; exit 2; }

echo "== 1/3 provenance manifest check =="
"$PY" scripts/make_provenance_manifest.py --check || {
    echo "verify_reproduction: manifest check FAILED; committed inputs differ from the manifest." >&2
    exit 1
}

echo "== 2/3 regenerate in sandbox =="
SANDBOX="$(mktemp -d "${TMPDIR:-/tmp}/qme_repro.XXXXXX")" || exit 2
trap 'rm -rf "$SANDBOX"' EXIT
mkdir -p "$SANDBOX/data"
cp data/results.json "$SANDBOX/data/"
QME_ROOT="$SANDBOX" "$PY" scripts/d1_offset_verdict_70_560.py >"$SANDBOX/regen.log" 2>&1 || {
    echo "verify_reproduction: generator failed; log follows" >&2
    cat "$SANDBOX/regen.log" >&2
    exit 2
}

echo "== 3/3 byte comparison =="
if cmp -s "$SANDBOX/data/d1_corrected_offsets.json" data/d1_corrected_offsets.json; then
    echo "PASS: d1_corrected_offsets.json regenerated byte-identically from committed inputs."
    echo "      (verdict FAIL, sd 0.31 V over n=4; see the artifact for the numbers.)"
    exit 0
else
    echo "DIFF REPORT: regenerated artifact differs from the committed copy:" >&2
    diff -u data/d1_corrected_offsets.json "$SANDBOX/data/d1_corrected_offsets.json" >&2
    exit 1
fi
